# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 22:27
from __future__ import unicode_literals

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import idm_core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=idm_core.models.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('0', 'not known'), ('1', 'male'), ('2', 'female'), ('9', 'not applicable')], default='0', max_length=1)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('primary_username', models.CharField(blank=True, max_length=32)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('deceased', models.BooleanField(default=False)),
                ('state', django_fsm.FSMField(choices=[('new', 'new'), ('pending_claim', 'pending claim'), ('active', 'active'), ('dormant', 'dormant')], default='new', max_length=50)),
                ('claim_code', models.UUIDField(blank=True, null=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idm_core.Identity')),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=idm_core.models.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idm_core.Identity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
