# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 16:09
from __future__ import unicode_literals

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import idm_identity.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=idm_identity.models.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('pronouns', models.TextField(blank=True, help_text='subject[ object[ possessive-determiner[ possessive-pronoun[ reflexive]]]]')),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('primary_username', models.CharField(blank=True, max_length=32)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('deceased', models.BooleanField(default=False)),
                ('state', django_fsm.FSMField(default='new', max_length=50)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='gender.Gender')),
                ('legal_gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people_legally', to='gender.Gender')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idm_identity.Identity')),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=idm_identity.models.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idm_identity.Identity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
