# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-15 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecontext',
            name='aspect_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagecontext',
            name='instructions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagecontext',
            name='max_height',
            field=models.IntegerField(default=2160),
        ),
        migrations.AddField(
            model_name='imagecontext',
            name='max_width',
            field=models.IntegerField(default=3840),
        ),
    ]
