# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20170815_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set([]),
        ),
        migrations.RunSQL(
            "CREATE UNIQUE INDEX image_one_approved ON image_image (identity_id, context_id) WHERE state = 'approved'",
            "DROP INDEX image_one_approved",
        ),
    ]
