# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-01 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20170820_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecontext',
            name='aspect_ratio',
        ),
        migrations.AddField(
            model_name='imagecontext',
            name='max_aspect_ratio_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagecontext',
            name='max_aspect_ratio_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagecontext',
            name='min_aspect_ratio_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagecontext',
            name='min_aspect_ratio_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagecontext',
            name='prefer_jpeg',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='image/%Y/%m/%d/'),
        ),
    ]
