# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 22:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion

from idm_core.name.fields import JSONSchemaField
from idm_core.name.models import components_schema


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idm_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain', models.TextField(blank=True)),
                ('plain_full', models.TextField(blank=True)),
                ('marked_up', models.TextField(blank=True)),
                ('familiar', models.TextField(blank=True)),
                ('sort', models.TextField(blank=True)),
                ('first', models.TextField(blank=True)),
                ('last', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('space_delimited', models.BooleanField(default=True)),
                ('components', JSONSchemaField(schema=components_schema)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NameContext',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('label', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='name',
            name='contexts',
            field=models.ManyToManyField(to='name.NameContext'),
        ),
        migrations.AddField(
            model_name='name',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='idm_core.Identity'),
        ),
    ]
