# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-20 19:22
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0003_name_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='state',
            field=django_fsm.FSMField(choices=[('proposed', 'proposed'), ('accepted', 'accepted'),
                                               ('rejected', 'rejected'), ('previous', 'previous')],
                                      default='proposed', max_length=50),
        ),
    ]
