# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-20 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0004_name_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='namecontext',
            name='subject_to_acceptance',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
