# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-20 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0006_update_name_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='namecontext',
            name='only_one_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='namecontext',
            name='subject_to_acceptance',
            field=models.BooleanField(default=True),
        ),
    ]
