# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0007_auto_20170820_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='active',
        ),
    ]
