# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import idm_core.org_relationship.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('effective_start_date', models.DateTimeField(blank=True, null=True)),
                ('effective_end_date', models.DateTimeField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('state', django_fsm.FSMField(choices=[('declined', 'Declined'), ('offered', 'Offered'), ('requested', 'Requested'), ('active', 'Active'), ('forthcoming', 'Forthcoming'), ('historic', 'Historic'), ('suspended', 'Suspended')], db_index=True, max_length=16, protected=True)),
                ('suspended', idm_core.org_relationship.models.FSMBooleanField(db_index=True, default=False, protected=True)),
                ('dependent_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org_relationship.Affiliation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AffiliationType',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('edu_person_affiliation_value', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('effective_start_date', models.DateTimeField(blank=True, null=True)),
                ('effective_end_date', models.DateTimeField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('state', django_fsm.FSMField(choices=[('declined', 'Declined'), ('offered', 'Offered'), ('requested', 'Requested'), ('active', 'Active'), ('forthcoming', 'Forthcoming'), ('historic', 'Historic'), ('suspended', 'Suspended')], db_index=True, max_length=16, protected=True)),
                ('suspended', idm_core.org_relationship.models.FSMBooleanField(db_index=True, default=False, protected=True)),
                ('dependent_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org_relationship.Role')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_relationship.RoleType'),
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_relationship.RoleType'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_relationship.AffiliationType'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationrole',
            unique_together=set([('type', 'organization')]),
        ),
    ]
