# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attests_object_id', models.PositiveIntegerField()),
                ('attests_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_id', models.UUIDField()),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=256)),
                ('identity_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDocumentPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attestation.SourceDocument')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDocumentType',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attestation.SourceDocumentType'),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='validated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validated_source_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attestation',
            name='source_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attestation.SourceDocument'),
        ),
    ]
