# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idm_core', '0002_identity_primary_name'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('attestation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='idm_core.Identity'),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='validated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validated_source_documents', to='idm_core.Identity'),
        ),
        migrations.AddField(
            model_name='attestation',
            name='source_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attestation.SourceDocument'),
        ),
        migrations.AddField(
            model_name='attestation',
            name='supports_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
