# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 11:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('identity', '0002_auto_20161212_1114'),
        ('attestation', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='validated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validated_source_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attestation',
            name='attests_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='attestation',
            name='source_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attestation.SourceDocument'),
        ),
    ]
