# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0002_auto_20170611_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcedocument',
            name='complete',
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='document',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
