# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0003_auto_20170725_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
