# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0004_sourcedocument_encrypted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcedocumentpage',
            name='source_document',
        ),
        migrations.DeleteModel(
            name='SourceDocumentPage',
        ),
    ]
