# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-10 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifier',
            name='primary',
            field=models.BooleanField(default=True),
        ),
    ]
