# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_auto_20161212_1114'),
        ('identifier', '0002_auto_20161212_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifiertype',
            name='applicable_to',
            field=models.ManyToManyField(to='identity.IdentityType'),
        ),
    ]
