# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 22:05
from __future__ import unicode_literals

import dirtyfields.dirtyfields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('org_relationship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attested_by', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('driving-license', 'Driving license'), ('passport', 'Passport'), ('national-identity-document', 'National identity document'), ('bill', 'Bill'), ('visa', 'Visa'), ('deed-poll', 'Deed poll'), ('other', 'Other')], max_length=32), default=[], size=None)),
                ('validated', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org_relationship.Affiliation')),
            ],
            options={
                'abstract': False,
                'ordering': ('person', 'order'),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContactContext',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attested_by', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('driving-license', 'Driving license'), ('passport', 'Passport'), ('national-identity-document', 'National identity document'), ('bill', 'Bill'), ('visa', 'Visa'), ('deed-poll', 'Deed poll'), ('other', 'Other')], max_length=32), default=[], size=None)),
                ('validated', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('value', models.EmailField(max_length=254)),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org_relationship.Affiliation')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.ContactContext')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='person.Person')),
            ],
            options={
                'abstract': False,
                'ordering': ('person', 'order'),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attested_by', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('driving-license', 'Driving license'), ('passport', 'Passport'), ('national-identity-document', 'National identity document'), ('bill', 'Bill'), ('visa', 'Visa'), ('deed-poll', 'Deed poll'), ('other', 'Other')], max_length=32), default=[], size=None)),
                ('validated', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('value', models.EmailField(max_length=254)),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org_relationship.Affiliation')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.ContactContext')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
            ],
            options={
                'abstract': False,
                'ordering': ('person', 'order'),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='address',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.ContactContext'),
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='telephone',
            unique_together=set([('person', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together=set([('person', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('person', 'order')]),
        ),
    ]
