# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('contact', '0001_initial'),
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telephone',
            name='affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relationship.Affiliation'),
        ),
        migrations.AddField(
            model_name='telephone',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.ContactContext'),
        ),
        migrations.AddField(
            model_name='telephone',
            name='identity_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='onlineaccount',
            name='affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relationship.Affiliation'),
        ),
        migrations.AddField(
            model_name='onlineaccount',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.ContactContext'),
        ),
        migrations.AddField(
            model_name='onlineaccount',
            name='identity_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='email',
            name='affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relationship.Affiliation'),
        ),
        migrations.AddField(
            model_name='email',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.ContactContext'),
        ),
        migrations.AddField(
            model_name='email',
            name='identity_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='address',
            name='affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relationship.Affiliation'),
        ),
        migrations.AddField(
            model_name='address',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.ContactContext'),
        ),
        migrations.AddField(
            model_name='address',
            name='identity_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='telephone',
            unique_together=set([('identity_content_type', 'identity_id', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='onlineaccount',
            unique_together=set([('identity_content_type', 'identity_id', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together=set([('identity_content_type', 'identity_id', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('identity_content_type', 'identity_id', 'order')]),
        ),
    ]
