# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 13:12
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('contact', '0002_auto_20170611_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='manage_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='address',
            name='managed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Application'),
        ),
        migrations.AddField(
            model_name='address',
            name='unmanaged_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='address',
            name='upstream_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='manage_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='email',
            name='managed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Application'),
        ),
        migrations.AddField(
            model_name='email',
            name='unmanaged_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='email',
            name='upstream_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='onlineaccount',
            name='manage_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='onlineaccount',
            name='managed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Application'),
        ),
        migrations.AddField(
            model_name='onlineaccount',
            name='unmanaged_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='onlineaccount',
            name='upstream_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='telephone',
            name='manage_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='telephone',
            name='managed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Application'),
        ),
        migrations.AddField(
            model_name='telephone',
            name='unmanaged_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='telephone',
            name='upstream_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
