# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20170615_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineAccountProvider',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('label', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='onlineaccount',
            name='screen_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineaccount',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contact.OnlineAccountProvider'),
            preserve_default=False,
        ),
    ]
