# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_unique_contact_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephoneType',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('label', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='telephone',
            name='value',
        ),
        migrations.AddField(
            model_name='telephone',
            name='external',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telephone',
            name='internal',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='telephone',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contact.TelephoneType'),
            preserve_default=False,
        ),
    ]
