# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmaymanagecontenttype',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationmaymanagecontenttype',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='application',
            name='manageable_content_types',
        ),
        migrations.AddField(
            model_name='application',
            name='manageable_content_types',
            field=models.ManyToManyField(to='contenttypes.ContentType'),
        ),
        migrations.DeleteModel(
            name='ApplicationMayManageContentType',
        ),
    ]
