# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20170618_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='manageable_content_types',
            field=models.ManyToManyField(blank=True, to='contenttypes.ContentType'),
        ),
    ]
