# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 18:38
from __future__ import unicode_literals

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import idm_core.identity.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('id', models.UUIDField(default=idm_core.identity.models.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=1024)),
                ('qualified_label', models.CharField(blank=True, max_length=1024)),
                ('sort_label', models.CharField(blank=True, max_length=1024)),
                ('primary_username', models.CharField(blank=True, max_length=32)),
                ('state', django_fsm.FSMField(choices=[('established', 'established'), ('active', 'active'), ('archived', 'archived'), ('suspended', 'suspended'), ('merged', 'merged')], default='established', max_length=50)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merged_from', to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationship', to='organization.Organization')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='organization.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationRelationshipType',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationTag',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='organizationrelationship',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationRelationshipType'),
        ),
        migrations.AddField(
            model_name='organization',
            name='relationships',
            field=models.ManyToManyField(through='organization.OrganizationRelationship', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tags',
            field=models.ManyToManyField(blank=True, to='organization.OrganizationTag'),
        ),
    ]
