# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('organization', '0002_auto_20170618_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
