# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_affiliation_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrelationshiptype',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
