# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170730_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliationtype',
            name='edu_person_affiliation_value',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='affiliationtype',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
