# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 10:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20170730_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodleianGroup',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='affiliation',
            name='congregation_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='congregation_affiliations', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='job_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='affiliationtype',
            name='metadata_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=[], size=None),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='bodleian_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.BodleianGroup'),
        ),
    ]
