# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('organization', '0006_auto_20170730_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliation',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='affiliation',
            name='order',
            field=models.PositiveSmallIntegerField(default=10000),
            preserve_default=False,
        ),
    ]
