# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20170730_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrelationshiptype',
            name='short_label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
