# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_organizationrelationshiptype_short_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationrelationshiptype',
            name='short_label',
        ),
        migrations.AddField(
            model_name='organization',
            name='short_label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
