# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20170809_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationrole',
            options={'permissions': (('can_merge_identity', 'can merge identity'), ('can_archive_identity', 'can archive identity'), ('can_activate_identity', 'can activate identity'), ('can_restore_identity', 'can restore identity'))},
        ),
    ]
