# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('name', '0001_initial'),
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='primary_name',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_name_of', to='name.Name'),
        ),
        migrations.AddField(
            model_name='identity',
            name='role_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relationship.RoleType'),
        ),
        migrations.AddField(
            model_name='identity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.IdentityType'),
        ),
    ]
