# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_auto_20170611_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='principal_name',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=256, null=True, unique=True),
        ),
    ]
