# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_user_principal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='principal_name',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, unique=True),
        ),
    ]
